Repository ballerina-platform/ballerina-standard-library, pull requests merged in 2020-10, with the labels that each got.

#41 Add Email, Socket and FTP module builds to dashboard
  README.md
Labels: Type/Task, module/email, module/ftp, module/socket

#224 Add FTP module to pipeline
  release/resources/stdlib_modules.json
Labels: module/ftp

#229 Add retry configs for HTTP client in release pipeline
  release/src/commons/constants.bal
  release/src/publish/publish.bal
  release/src/release/release.bal
Labels: Type/Improvement, module/release
