Repository ballerina-platform/ballerina-standard-library, pull requests merged in 2020-11, with the labels that each got.

#567 Update publish pipeline to check workflow run status
  release/src/commons/constants.bal
  release/src/commons/functions.bal
  release/src/commons/records.bal
  release/src/publish/publish.bal
  release/src/publish/utils/constants.bal
  release/src/release/release.bal
  release/src/release/utils/constants.bal
Labels: area/build

#589 Ignore build fails of non-dependee module build failures when publishing snapshots
  release/src/publish/publish.bal
Labels: Type/Improvement, area/build

#590 Ignore all the build fails and continue the process with warning
  release/src/publish/publish.bal
Labels: Type/Task, area/build

#609 Using GitHub CLI to raise PR
  .github/workflows/dependency_graph.yml
Labels: area/build
